type NodeType = 'city' | 'gym' | 'capture' | 'move' | 'league';

type Node = {
  id: number;
  x: number;
  y: number;
  type: NodeType;
  sector: string;
  event: boolean;
};

export const nodes: Node[] = [
  { id: 1, x: 28.8, y: 65.6, type: 'city', sector: 'Pallet', event: false },
  { id: 2, x: 26.6, y: 48.8, type: 'city', sector: 'Viridian', event: false },
  { id: 3, x: 28.8, y: 24.2, type: 'city', sector: 'Pewter', event: false },
  { id: 4, x: 51.5, y: 20.65, type: 'city', sector: 'Cerulean', event: false },
  { id: 5, x: 67.5, y: 33, type: 'city', sector: 'Lavender', event: false },
  { id: 6, x: 51.8, y: 34.8, type: 'city', sector: 'Saffron', event: false },
  { id: 7, x: 40.4, y: 34.15, type: 'city', sector: 'Celadon', event: false },
  {
    id: 8,
    x: 51.95,
    y: 48.95,
    type: 'city',
    sector: 'Vermilion',
    event: false,
  },
  { id: 9, x: 46.95, y: 70.7, type: 'city', sector: 'Fuchsia', event: false },
  { id: 10, x: 33.8, y: 73, type: 'city', sector: 'Cinnabar', event: false },
  { id: 11, x: 27.5, y: 61.7, type: 'move', sector: 'pink', event: false },
  { id: 12, x: 27.2, y: 56.4, type: 'move', sector: 'pink', event: true },
  { id: 13, x: 24.5, y: 54.2, type: 'move', sector: 'pink', event: false },
  { id: 14, x: 27.6, y: 44.4, type: 'move', sector: 'pink', event: true },
  { id: 15, x: 25.5, y: 40.3, type: 'move', sector: 'pink', event: false },
  { id: 16, x: 28.0, y: 38.0, type: 'move', sector: 'pink', event: false },
  { id: 17, x: 26.1, y: 34.4, type: 'move', sector: 'pink', event: true },
  { id: 18, x: 23.4, y: 32.8, type: 'move', sector: 'pink', event: false },
  { id: 19, x: 23.1, y: 27.8, type: 'move', sector: 'pink', event: false },
  { id: 20, x: 25.9, y: 26.2, type: 'move', sector: 'pink', event: false },
  { id: 21, x: 29.1, y: 20.0, type: 'move', sector: 'pink', event: true },
  { id: 22, x: 30.3, y: 15.3, type: 'move', sector: 'pink', event: false },
  { id: 23, x: 32.4, y: 18.0, type: 'move', sector: 'pink', event: true },
  { id: 24, x: 35.2, y: 18.0, type: 'move', sector: 'pink', event: false },
  { id: 25, x: 36.3, y: 22.5, type: 'move', sector: 'pink', event: false },
  { id: 26, x: 40.5, y: 22.4, type: 'move', sector: 'green', event: false },
  { id: 27, x: 41.5, y: 17.8, type: 'move', sector: 'green', event: true },
  { id: 28, x: 44.2, y: 18.8, type: 'move', sector: 'green', event: false },
  { id: 29, x: 47.1, y: 18.7, type: 'move', sector: 'green', event: false },
  { id: 30, x: 48.8, y: 22.7, type: 'move', sector: 'green', event: true },
  { id: 31, x: 57.9, y: 18.7, type: 'move', sector: 'green', event: false },
  { id: 32, x: 62.0, y: 19.9, type: 'move', sector: 'green', event: true },
  { id: 33, x: 64.8, y: 20.1, type: 'move', sector: 'green', event: false },
  { id: 34, x: 67.4, y: 22.1, type: 'move', sector: 'green', event: false },
  { id: 35, x: 70.3, y: 23.5, type: 'move', sector: 'green', event: true },
  { id: 36, x: 73.0, y: 25.0, type: 'move', sector: 'green', event: false },
  { id: 37, x: 73.4, y: 30.2, type: 'move', sector: 'green', event: true },
  { id: 38, x: 64.9, y: 35.2, type: 'move', sector: 'green', event: true },
  { id: 39, x: 62.0, y: 35.1, type: 'move', sector: 'green', event: false },
  { id: 40, x: 57.9, y: 35.2, type: 'move', sector: 'green', event: true },
  { id: 41, x: 54.5, y: 28.0, type: 'move', sector: 'green', event: true },
  { id: 42, x: 51.6, y: 28.3, type: 'move', sector: 'green', event: false },
  { id: 43, x: 49.2, y: 35.4, type: 'move', sector: 'green', event: false },
  { id: 44, x: 46.3, y: 34.0, type: 'move', sector: 'green', event: true },
  { id: 45, x: 51.9, y: 41.8, type: 'move', sector: 'blue', event: true },
  { id: 46, x: 54.5, y: 44.1, type: 'move', sector: 'blue', event: false },
  { id: 47, x: 57.9, y: 49.6, type: 'move', sector: 'blue', event: true },
  { id: 48, x: 62.1, y: 45.5, type: 'move', sector: 'blue', event: true },
  { id: 49, x: 65.0, y: 45.8, type: 'move', sector: 'blue', event: false },
  { id: 50, x: 67.7, y: 49.6, type: 'move', sector: 'blue', event: true },
  { id: 51, x: 62.2, y: 53.4, type: 'move', sector: 'blue', event: false },
  { id: 52, x: 65.1, y: 53.6, type: 'move', sector: 'blue', event: true },
  { id: 53, x: 70.7, y: 41.4, type: 'move', sector: 'blue', event: false },
  { id: 54, x: 71.2, y: 46.6, type: 'move', sector: 'blue', event: true },
  { id: 55, x: 71.4, y: 51.6, type: 'move', sector: 'blue', event: false },
  { id: 56, x: 70.4, y: 57.2, type: 'move', sector: 'blue', event: false },
  { id: 57, x: 67.6, y: 58.4, type: 'move', sector: 'blue', event: true },
  { id: 58, x: 65.4, y: 63.0, type: 'move', sector: 'blue', event: false },
  { id: 59, x: 64.6, y: 68.1, type: 'move', sector: 'blue', event: false },
  { id: 60, x: 62.2, y: 70.8, type: 'move', sector: 'blue', event: true },
  { id: 61, x: 58.0, y: 70.8, type: 'move', sector: 'blue', event: false },
  { id: 62, x: 55.5, y: 73.3, type: 'move', sector: 'blue', event: false },
  { id: 63, x: 52.7, y: 72.0, type: 'move', sector: 'blue', event: true },
  { id: 64, x: 44.6, y: 71.2, type: 'move', sector: 'red', event: true },
  { id: 65, x: 40.7, y: 69.0, type: 'move', sector: 'red', event: false },
  { id: 66, x: 36.4, y: 64.4, type: 'move', sector: 'red', event: true },
  { id: 67, x: 36.5, y: 59.0, type: 'move', sector: 'red', event: false },
  { id: 68, x: 36.5, y: 53.6, type: 'move', sector: 'red', event: true },
  { id: 69, x: 36.5, y: 48.3, type: 'move', sector: 'red', event: false },
  { id: 70, x: 36.4, y: 43.0, type: 'move', sector: 'red', event: false },
  { id: 71, x: 36.4, y: 37.7, type: 'move', sector: 'red', event: false },
  { id: 72, x: 49.6, y: 79.4, type: 'move', sector: 'red', event: false },
  { id: 73, x: 46.7, y: 82.0, type: 'move', sector: 'red', event: false },
  { id: 74, x: 40.7, y: 82.3, type: 'move', sector: 'red', event: true },
  { id: 75, x: 36.3, y: 82.2, type: 'move', sector: 'red', event: true },
  { id: 76, x: 33.4, y: 81.2, type: 'move', sector: 'red', event: true },

  { id: 83, x: 24.6, y: 20.5, type: 'capture', sector: 'pink', event: false },

  {
    id: 999999,
    x: 47,
    y: 60,
    type: 'league',
    sector: 'grey',
    event: false,
  },
];
